import 'package:auth_app/firebase_options.dart'; // Generated by FlutterFire
import 'package:auth_app/splash_screen.dart';   // Import the new splash screen
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:firebase_app_check/firebase_app_check.dart'; // Import Firebase App Check

void main() async {
  // Ensure that Flutter bindings are initialized before calling Firebase.
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase using the generated options file.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // NEW: Initialize Firebase App Check
  // This helps protect your backend from abuse by verifying that requests
  // are coming from your genuine app.
  await FirebaseAppCheck.instance.activate(
    // You can also use .debugProvider for testing in debug mode.
    androidProvider: AndroidProvider.playIntegrity,
    // appleProvider: AppleProvider.appAttest, // For iOS
  );
  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Auth Demo',
      // Hide the debug banner
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        // Define a modern color scheme
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
        // Style for input fields
        inputDecorationTheme: InputDecorationTheme(
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
        // Style for buttons
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.deepPurple,
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(vertical: 16),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        ),
      ),
      // Set the SplashScreen as the initial screen (home).
      home: const SplashScreen(),
    );
  }
}
